// ============================================================================
//  DATA  —  Every entry here becomes a full "character select" card + detail
//  page + 3D animation automatically. To add a new rocket or satellite, just
//  copy an existing object and fill in the fields. Nothing else to change.
// ============================================================================
//
//  FIELD GUIDE
//  -----------
//  id          unique short slug (used in the URL)
//  name        display name (shown in LARGE print)
//  nickname    short tagline under the name
//  mission     the famous mission it is remembered for (BIG print on the page)
//  country     flag emoji + country
//  agency      who operated it
//  builtBy     manufacturer / who built it
//  firstFlight year (or launch year for satellites)
//  status      Retired / Active / Operational / etc.
//  facts       quick stat chips  { label, value }
//  where       where it went
//  why         why it went there
//  discovered  what was discovered / achieved
//  destination one of the scene keys below (drives the 3D animation backdrop)
//                rockets:    LEO, GTO, Moon, Mars, Sun, DeepSpace, Suborbital
//                satellites: LEO, Moon, Mars, Jupiter, Saturn, Sun, Pluto,
//                            Interstellar, Comet, L2, Venus
//  viz         parameters for the procedural 3D model (see scene3d.js)
//  anatomy     optional [{part, desc}] — enables the "Parts / Anatomy" view
//
// ============================================================================

export const ROCKETS = [
  {
    id: "saturn-v",
    name: "Saturn V",
    nickname: "The rocket that took humans to the Moon",
    mission: "Apollo 11 — First humans on the Moon",
    country: "United States",
    agency: "NASA",
    builtBy: "Boeing, North American Aviation & Douglas Aircraft",
    firstFlight: 1967,
    status: "Retired (1973)",
    facts: [
      { label: "Height", value: "110.6 m" },
      { label: "Mass", value: "2,970 t" },
      { label: "Stages", value: "3" },
      { label: "Thrust", value: "35,100 kN" },
      { label: "Payload to Moon", value: "48.6 t" },
    ],
    where: "Low Earth orbit, then a trans-lunar trajectory to the Moon, ~384,000 km away.",
    why: "The United States built Saturn V to win the Space Race and land astronauts on the Moon before the decade of the 1960s was out, as President Kennedy had promised.",
    discovered: "On 20 July 1969 Apollo 11 delivered Neil Armstrong and Buzz Aldrin to the lunar surface — the first time humans walked on another world. Saturn V flew 13 times and never lost a crew. It remains the most powerful rocket to fly a completed operational program.",
    whatHappened: "Apollo 4 proved the rocket unmanned in November 1967. Apollo 8 carried the first humans around the Moon in December 1968. On 20 July 1969, Apollo 11 landed Armstrong and Aldrin on the Sea of Tranquility. Five more crews landed on the Moon in subsequent missions. The final Saturn V launched the Skylab space station in May 1973.",
    destination: "Moon",
    viz: { stages: [ {len: 42, rad: 5}, {len: 25, rad: 5}, {len: 18, rad: 3.3} ], nose: 12, fins: 4, color: "#f2f2f2", accent: "#111", boosters: 0, target: "Moon" },
    anatomy: [
      { part: "Launch Escape System", desc: "A small tower rocket that could yank the crew capsule to safety in an emergency during launch." },
      { part: "Command & Service Module", desc: "The crew cabin and its support section — the only part that came home to Earth." },
      { part: "Lunar Module", desc: "Stored in a cone below the CSM; the spider-like craft that actually landed on the Moon." },
      { part: "Third Stage (S-IVB)", desc: "Fired twice: first to reach orbit, then again to push the spacecraft toward the Moon." },
      { part: "Second Stage (S-II)", desc: "Five J-2 engines burning liquid hydrogen to carry the stack toward orbital speed." },
      { part: "First Stage (S-IC)", desc: "Five giant F-1 engines burning kerosene and oxygen — 3.4 million kg of thrust at liftoff." },
    ],
  },
  {
    id: "space-shuttle",
    name: "Space Shuttle",
    nickname: "The world's first reusable spaceplane",
    mission: "STS-1 & 135 flights building the ISS and launching Hubble",
    country: "United States",
    agency: "NASA",
    builtBy: "Rockwell International",
    firstFlight: 1981,
    status: "Retired (2011)",
    facts: [
      { label: "Height", value: "56 m" },
      { label: "Mass", value: "2,030 t" },
      { label: "Flights", value: "135" },
      { label: "Payload to LEO", value: "27.5 t" },
      { label: "Crew", value: "up to 8" },
    ],
    where: "Low Earth orbit, typically 300–600 km up.",
    why: "NASA wanted a reusable vehicle that could carry large crews and cargo, deploy and repair satellites, and build a space station.",
    discovered: "Over 30 years the Shuttle launched the Hubble Space Telescope, built most of the International Space Station, and flew 355 people. Its two tragedies — Challenger (1986) and Columbia (2003) — reshaped how the world thinks about spaceflight safety.",
    whatHappened: "Columbia flew the first mission in April 1981. Over three decades, five orbiters carried 355 people across 135 missions, building most of the ISS and deploying Hubble. Challenger was lost 73 seconds after launch on 28 January 1986. Columbia broke apart during re-entry on 1 February 2003. Atlantis flew the final mission in July 2011.",
    destination: "LEO",
    viz: { orbiter: true, tank: {len: 47, rad: 4.2, color: "#c8712d"}, boosters: 2, boosterLen: 45, boosterRad: 1.8, color: "#f2f2f2", accent: "#222", target: "LEO" },
  },
  {
    id: "falcon-9",
    name: "Falcon 9",
    nickname: "The first orbital rocket to land and fly again",
    mission: "Reusable flight & crewed missions to the ISS",
    country: "United States",
    agency: "SpaceX",
    builtBy: "SpaceX",
    firstFlight: 2010,
    status: "Active",
    facts: [
      { label: "Height", value: "70 m" },
      { label: "Mass", value: "549 t" },
      { label: "Engines", value: "9 (Merlin)" },
      { label: "Payload to LEO", value: "22.8 t" },
      { label: "Reusable", value: "Yes" },
    ],
    where: "Low Earth orbit and geostationary transfer orbit; boosters return to land on a droneship or launch pad.",
    why: "SpaceX set out to slash the cost of spaceflight by recovering and reflying the expensive first stage instead of throwing it away.",
    discovered: "In 2015 Falcon 9 became the first orbital-class rocket to land its booster upright, and in 2020 it returned human spaceflight to American soil with Crew Dragon. Individual boosters have now flown more than 20 times each.",
    whatHappened: "First launched in June 2010. On 21 December 2015, the first stage landed vertically at Cape Canaveral, making history as the first orbital-class booster ever recovered. In May 2020, Crew Dragon Demo-2 carried astronauts to the ISS, restoring American crewed launch capability. Individual boosters have since been reflown more than 20 times each.",
    destination: "LEO",
    viz: { stages: [ {len: 42, rad: 1.85}, {len: 13, rad: 1.85} ], nose: 6, fins: 4, gridfins: true, color: "#f7f7f7", accent: "#111", boosters: 0, target: "LEO" },
  },
  {
    id: "falcon-heavy",
    name: "Falcon Heavy",
    nickname: "Two boosters that land side by side",
    mission: "Launched a Tesla Roadster toward Mars' orbit (2018)",
    country: "United States",
    agency: "SpaceX",
    builtBy: "SpaceX",
    firstFlight: 2018,
    status: "Active",
    facts: [
      { label: "Height", value: "70 m" },
      { label: "Cores", value: "3" },
      { label: "Engines", value: "27" },
      { label: "Payload to LEO", value: "63.8 t" },
      { label: "Thrust", value: "22,800 kN" },
    ],
    where: "Everything from Earth orbit to deep space — its test flight sent a car past the orbit of Mars.",
    why: "SpaceX needed a heavy-lift vehicle for large payloads and deep-space missions while keeping the boosters reusable.",
    discovered: "On its 2018 debut, two side boosters touched down together in a synchronized landing while a cherry-red Tesla with a mannequin 'Starman' sailed into a solar orbit reaching beyond Mars.",
    whatHappened: "Its February 2018 debut launched a cherry-red Tesla Roadster into a heliocentric orbit reaching past Mars, while both side boosters landed simultaneously at Cape Canaveral. It has since launched heavy national-security payloads and deep-space missions including NASA's Psyche asteroid probe.",
    destination: "DeepSpace",
    viz: { stages: [ {len: 42, rad: 1.85}, {len: 13, rad: 1.85} ], nose: 6, fins: 4, gridfins: true, color: "#f7f7f7", accent: "#111", boosters: 2, boosterLen: 42, boosterRad: 1.85, target: "DeepSpace" },
  },
  {
    id: "soyuz",
    name: "Soyuz",
    nickname: "The most-flown rocket in history",
    mission: "Six decades of carrying cosmonauts and crews to orbit",
    country: "Russia (USSR)",
    agency: "Roscosmos",
    builtBy: "RKK Energia / Progress",
    firstFlight: 1966,
    status: "Active",
    facts: [
      { label: "Height", value: "46 m" },
      { label: "Lineage", value: "R-7 (1957)" },
      { label: "Flights", value: "1,900+" },
      { label: "Payload to LEO", value: "8.2 t" },
      { label: "Boosters", value: "4" },
    ],
    where: "Low Earth orbit — the space stations Salyut, Mir, and the ISS.",
    why: "Derived from the world's first ICBM (the R-7 that launched Sputnik), Soyuz became the Soviet and Russian workhorse for reliable, repeatable human spaceflight.",
    discovered: "From 2011 to 2020, Soyuz was the only way any astronaut — American, European, Japanese or Russian — could reach the ISS. Its distinctive cluster of four tapered boosters has flown more often than any other launch vehicle ever built.",
    whatHappened: "Derived from the R-7 that launched Sputnik, Soyuz has flown more than 1,900 times since 1966. From 2011 to 2020 it was the sole means of transporting any astronaut to the ISS. A 2018 in-flight abort demonstrated the launch escape system, safely returning the crew after a booster failure during ascent.",
    destination: "LEO",
    viz: { stages: [ {len: 28, rad: 1.4}, {len: 10, rad: 1.3} ], nose: 8, fins: 0, color: "#dfe4ea", accent: "#2f5f2f", boosters: 4, boosterLen: 19, boosterRad: 1.3, tapered: true, target: "LEO" },
  },
  {
    id: "atlas-v",
    name: "Atlas V",
    nickname: "America's reliable deep-space workhorse",
    mission: "Launched Curiosity, New Horizons & Perseverance",
    country: "United States",
    agency: "United Launch Alliance",
    builtBy: "Lockheed Martin",
    firstFlight: 2002,
    status: "Active (retiring)",
    facts: [
      { label: "Height", value: "58 m" },
      { label: "Engine", value: "RD-180" },
      { label: "Boosters", value: "0–5" },
      { label: "Payload to LEO", value: "18.8 t" },
      { label: "Success rate", value: "~99%" },
    ],
    where: "Earth orbit, the Moon, Pluto, Mars — wherever a high-value robotic mission needed to go.",
    why: "NASA and the U.S. military needed an extremely reliable rocket for irreplaceable science probes and national-security satellites.",
    discovered: "Atlas V sent New Horizons racing toward Pluto, delivered the Curiosity and Perseverance rovers to Mars, and launched Juno to Jupiter — one of the most trusted rockets in spaceflight.",
    whatHappened: "First launched in August 2002, it has maintained one of the highest reliability records of any rocket. It delivered the Curiosity and Perseverance rovers to Mars, launched New Horizons toward Pluto, and sent the Juno spacecraft into Jupiter orbit.",
    destination: "Mars",
    viz: { stages: [ {len: 32, rad: 1.9}, {len: 12, rad: 1.5} ], nose: 10, fins: 0, color: "#e8e8e8", accent: "#b33", boosters: 2, boosterLen: 17, boosterRad: 0.8, target: "Mars" },
  },
  {
    id: "delta-iv-heavy",
    name: "Delta IV Heavy",
    nickname: "The fireball rocket",
    mission: "Launched the Parker Solar Probe toward the Sun",
    country: "United States",
    agency: "United Launch Alliance",
    builtBy: "Boeing",
    firstFlight: 2004,
    status: "Retired (2024)",
    facts: [
      { label: "Height", value: "72 m" },
      { label: "Cores", value: "3" },
      { label: "Fuel", value: "Liquid hydrogen" },
      { label: "Payload to LEO", value: "28.8 t" },
      { label: "Thrust", value: "9,420 kN" },
    ],
    where: "High-energy orbits, deep space and toward the Sun.",
    why: "It was the U.S.'s most powerful rocket for a decade, reserved for the heaviest spy satellites and the highest-energy science missions.",
    discovered: "Famous for the orange fireball of hydrogen that engulfs it at ignition, Delta IV Heavy launched the Parker Solar Probe on its record-breaking dive into the Sun's corona and lofted the first Orion capsule test flight.",
    whatHappened: "Flew 16 missions between 2004 and 2024. In 2018 it launched the Parker Solar Probe toward the Sun at the highest launch energy ever achieved. Known for the dramatic hydrogen fireball that engulfs its base at ignition, it flew its final mission in April 2024.",
    destination: "Sun",
    viz: { stages: [ {len: 40, rad: 2.5}, {len: 12, rad: 2.5} ], nose: 9, fins: 0, color: "#d9822b", accent: "#7a4a1a", boosters: 2, boosterLen: 40, boosterRad: 2.5, target: "Sun" },
  },
  {
    id: "ariane-5",
    name: "Ariane 5",
    nickname: "Europe's flawless heavy-lifter",
    mission: "Launched the James Webb Space Telescope (2021)",
    country: "Europe",
    agency: "ESA / Arianespace",
    builtBy: "Airbus (ArianeGroup)",
    firstFlight: 1996,
    status: "Retired (2023)",
    facts: [
      { label: "Height", value: "52 m" },
      { label: "Boosters", value: "2 solid" },
      { label: "Payload to GTO", value: "10.9 t" },
      { label: "Flights", value: "117" },
      { label: "Streak", value: "82 in a row" },
    ],
    where: "Geostationary transfer orbit and, for JWST, a trajectory to the Sun–Earth L2 point 1.5 million km away.",
    why: "Europe wanted independent access to space and a dependable commercial launcher for the world's communications satellites.",
    discovered: "So precise was Ariane 5's 2021 launch of the James Webb Space Telescope that it saved enough fuel to roughly double the observatory's expected lifetime. Its final decades saw one of the best reliability records in the business.",
    whatHappened: "Flew 117 times from 1996 to 2023, achieving a streak of 82 consecutive successes. Its most celebrated launch was on Christmas Day 2021, placing the James Webb Space Telescope on a trajectory so precise that JWST's fuel reserves were roughly doubled, extending its expected lifetime.",
    destination: "GTO",
    viz: { stages: [ {len: 30, rad: 2.7}, {len: 10, rad: 2.7} ], nose: 8, fins: 0, color: "#dfe6ee", accent: "#1a4a8a", boosters: 2, boosterLen: 31, boosterRad: 1.5, target: "L2" },
  },
  {
    id: "long-march-5",
    name: "Long March 5",
    nickname: "China's heavy-lift giant",
    mission: "Launched Tianwen-1 to Mars & Chang'e-5 to the Moon",
    country: "China",
    agency: "CNSA",
    builtBy: "CALT",
    firstFlight: 2016,
    status: "Active",
    facts: [
      { label: "Height", value: "57 m" },
      { label: "Boosters", value: "4" },
      { label: "Payload to LEO", value: "25 t" },
      { label: "Payload to GTO", value: "14 t" },
      { label: "Nickname", value: "Fat Five" },
    ],
    where: "Earth orbit, the Moon and Mars.",
    why: "China needed a heavy rocket to build its own space station, return lunar samples, and reach other planets.",
    discovered: "Long March 5 launched the Tianwen-1 mission that put China's first rover on Mars, and Chang'e-5, which brought the first fresh Moon rocks back to Earth in over 40 years.",
    whatHappened: "After a 2017 failure that grounded the programme for three years, Long March 5 returned to flight in December 2019. It launched Tianwen-1 to Mars in 2020 and Chang'e-5 to the Moon, which returned 1.7 kg of lunar samples in December 2020 — the first fresh Moon rocks brought to Earth in over 40 years.",
    destination: "Mars",
    viz: { stages: [ {len: 31, rad: 2.5}, {len: 12, rad: 2.5} ], nose: 9, fins: 0, color: "#eef2f6", accent: "#c0392b", boosters: 4, boosterLen: 27, boosterRad: 1.7, target: "Mars" },
  },
  {
    id: "proton",
    name: "Proton",
    nickname: "The Soviet heavy-lift veteran",
    mission: "Launched the core modules of Mir & the ISS (Zarya)",
    country: "Russia (USSR)",
    agency: "Roscosmos",
    builtBy: "Khrunichev",
    firstFlight: 1965,
    status: "Retiring",
    facts: [
      { label: "Height", value: "53 m" },
      { label: "Stages", value: "3–4" },
      { label: "Payload to LEO", value: "23 t" },
      { label: "Flights", value: "400+" },
      { label: "Fuel", value: "Hypergolic" },
    ],
    where: "Earth orbit, geostationary orbit, the Moon and the planets.",
    why: "The Soviet Union needed a powerful rocket for space stations, interplanetary probes and heavy communications satellites.",
    discovered: "Proton lofted the first modules of both the Mir station and the ISS, and launched Soviet probes to Venus, Mars and the Moon across nearly six decades of service.",
    whatHappened: "Has flown more than 400 times since 1965. It launched the Salyut and Mir space station modules, the Zarya module that began ISS construction, and dozens of interplanetary probes to Venus, Mars, and the Moon. It uses hypergolic propellants that ignite on contact.",
    destination: "GTO",
    viz: { stages: [ {len: 21, rad: 3.5}, {len: 14, rad: 2}, {len: 6, rad: 2} ], nose: 7, fins: 0, color: "#dfe4ea", accent: "#555", boosters: 6, boosterLen: 21, boosterRad: 0.8, target: "GTO" },
  },
  {
    id: "titan-iiie",
    name: "Titan IIIE-Centaur",
    nickname: "The rocket that launched the Grand Tour",
    mission: "Launched Voyager 1 & 2 and the Viking Mars landers",
    country: "United States",
    agency: "NASA / USAF",
    builtBy: "Martin Marietta",
    firstFlight: 1974,
    status: "Retired (1977)",
    facts: [
      { label: "Height", value: "48 m" },
      { label: "Upper stage", value: "Centaur" },
      { label: "Boosters", value: "2 solid" },
      { label: "Flights", value: "7" },
      { label: "Payload to escape", value: "3.7 t" },
    ],
    where: "Escape trajectories to Mars and the outer planets.",
    why: "NASA needed a rocket powerful enough to fling heavy probes onto trajectories that would leave Earth behind entirely.",
    discovered: "In 1977 two Titan IIIE-Centaurs launched Voyager 1 and 2 on the Grand Tour of the outer solar system — spacecraft that are still transmitting from interstellar space today.",
    whatHappened: "Only seven were built, all for NASA's highest-priority science missions. In 1975 two Titan IIIE rockets launched the Viking spacecraft to Mars. In 1977 two more sent Voyager 1 and 2 on the Grand Tour of the outer planets — both are still transmitting from interstellar space nearly 50 years later.",
    destination: "DeepSpace",
    viz: { stages: [ {len: 23, rad: 3}, {len: 8, rad: 3}, {len: 9, rad: 1.5} ], nose: 7, fins: 0, color: "#e6e6e6", accent: "#333", boosters: 2, boosterLen: 26, boosterRad: 1.6, target: "DeepSpace" },
  },
  {
    id: "mercury-redstone",
    name: "Mercury-Redstone",
    nickname: "America's first crewed rocket",
    mission: "Sent Alan Shepard to space in 1961",
    country: "United States",
    agency: "NASA",
    builtBy: "Chrysler / von Braun's team",
    firstFlight: 1960,
    status: "Retired (1961)",
    facts: [
      { label: "Height", value: "25 m" },
      { label: "Stages", value: "1" },
      { label: "Flight", value: "Suborbital" },
      { label: "Thrust", value: "350 kN" },
      { label: "Crewed flights", value: "2" },
    ],
    where: "A suborbital arc reaching about 187 km before splashing down in the Atlantic.",
    why: "The U.S. needed to put a human in space quickly to answer the Soviet Union's early lead in the Space Race.",
    discovered: "On 5 May 1961 Alan Shepard rode a Mercury-Redstone on a 15-minute suborbital hop to become the first American in space, three weeks after Yuri Gagarin's orbital flight.",
    whatHappened: "On 5 May 1961 it carried Alan Shepard on a 15-minute suborbital arc to 187 km altitude, making him the first American in space. Gus Grissom followed in July 1961. The two flights validated the Mercury capsule and paved the way for John Glenn's orbital mission.",
    destination: "Suborbital",
    viz: { stages: [ {len: 18, rad: 0.9} ], nose: 6, fins: 4, color: "#f2f2f2", accent: "#111", boosters: 0, target: "Suborbital" },
  },
  {
    id: "n1",
    name: "N1",
    nickname: "The Soviet Moon rocket that never made it",
    mission: "The USSR's answer to Saturn V",
    country: "Russia (USSR)",
    agency: "OKB-1",
    builtBy: "Sergei Korolev's bureau",
    firstFlight: 1969,
    status: "Cancelled (1974)",
    facts: [
      { label: "Height", value: "105 m" },
      { label: "Engines (stage 1)", value: "30" },
      { label: "Thrust", value: "45,400 kN" },
      { label: "Attempts", value: "4 (all failed)" },
      { label: "Payload to LEO", value: "95 t" },
    ],
    where: "Intended for lunar orbit and a Soviet Moon landing that never happened.",
    why: "The Soviet Union raced to beat America to the Moon, but attempted it with thirty first-stage engines that proved impossible to coordinate.",
    discovered: "All four N1 launches failed, one in the largest non-nuclear explosion in history. Its cancellation ended the Soviet crewed lunar program — but its NK-33 engines later flew on American rockets decades on.",
    whatHappened: "All four launch attempts between 1969 and 1972 failed before the rocket cleared the lower atmosphere. The second attempt in July 1969 produced one of the largest non-nuclear explosions in history when the rocket fell back onto the pad seconds after liftoff. The programme was cancelled in 1974, and its existence was not publicly acknowledged until the 1990s.",
    destination: "Moon",
    viz: { stages: [ {len: 30, rad: 8.5}, {len: 20, rad: 5.5}, {len: 12, rad: 4} ], nose: 14, fins: 0, tapered: true, color: "#dfe4ea", accent: "#777", boosters: 0, target: "Moon" },
  },
  {
    id: "sls",
    name: "Space Launch System",
    nickname: "NASA's rocket back to the Moon",
    mission: "Artemis I — around the Moon and back (2022)",
    country: "United States",
    agency: "NASA",
    builtBy: "Boeing, Northrop Grumman & Aerojet",
    firstFlight: 2022,
    status: "Active",
    facts: [
      { label: "Height", value: "98 m" },
      { label: "Thrust", value: "39,100 kN" },
      { label: "Boosters", value: "2 solid" },
      { label: "Payload to LEO", value: "95 t" },
      { label: "Program", value: "Artemis" },
    ],
    where: "The Moon — carrying the Orion crew capsule to lunar orbit and beyond.",
    why: "NASA is returning astronauts to the Moon under the Artemis program to establish a lasting presence and prepare for Mars.",
    discovered: "On its 2022 debut, SLS sent an uncrewed Orion capsule around the Moon and back, the most powerful rocket NASA has flown since Saturn V and the first step of a planned return of humans to the lunar surface.",
    whatHappened: "Artemis I launched on 16 November 2022, sending an uncrewed Orion capsule on a 25-day trip around the Moon and back. The mission tested the heat shield at lunar-return speeds and validated the rocket for crewed flights. SLS is the most powerful rocket NASA has flown since Saturn V.",
    destination: "Moon",
    viz: { stages: [ {len: 60, rad: 4.1}, {len: 14, rad: 2.7} ], nose: 12, fins: 0, color: "#d9822b", accent: "#e8e8e8", boosters: 2, boosterLen: 54, boosterRad: 1.8, target: "Moon" },
  },
  {
    id: "starship",
    name: "Starship",
    nickname: "The biggest rocket ever built",
    mission: "A fully reusable ship aimed at the Moon and Mars",
    country: "United States",
    agency: "SpaceX",
    builtBy: "SpaceX",
    firstFlight: 2023,
    status: "In testing",
    facts: [
      { label: "Height", value: "121 m" },
      { label: "Engines", value: "33 (Raptor)" },
      { label: "Thrust", value: "74,400 kN" },
      { label: "Payload to LEO", value: "100+ t" },
      { label: "Reusable", value: "Fully" },
    ],
    where: "Designed for Earth orbit, the Moon and ultimately Mars.",
    why: "SpaceX is building Starship to make humanity multi-planetary by driving launch costs down through complete, rapid reuse of both stages.",
    discovered: "The most powerful rocket ever to fly, Starship has demonstrated the catch of its giant Super Heavy booster by the launch tower's arms — a landing technique never attempted before. NASA has chosen a version of it to land the next astronauts on the Moon.",
    whatHappened: "The first integrated flight test in April 2023 ended in a mid-flight breakup over the Gulf of Mexico. Subsequent tests demonstrated stage separation, controlled re-entry of the upper stage, and booster return to the launch site. In October 2024, the launch tower's mechanical arms caught the returning Super Heavy booster in mid-air — a technique never attempted before.",
    destination: "Mars",
    viz: { stages: [ {len: 71, rad: 4.5}, {len: 50, rad: 4.5} ], nose: 14, fins: 4, gridfins: true, color: "#b8bcc0", accent: "#222", boosters: 0, target: "Mars" },
  },
  {
    id: "vostok",
    name: "Vostok",
    nickname: "The rocket that launched the first human",
    mission: "Yuri Gagarin — first person in space (1961)",
    country: "Russia (USSR)",
    agency: "OKB-1",
    builtBy: "Sergei Korolev's bureau",
    firstFlight: 1960,
    status: "Retired (1963)",
    facts: [
      { label: "Height", value: "38 m" },
      { label: "Boosters", value: "4" },
      { label: "Based on", value: "R-7 ICBM" },
      { label: "Payload to LEO", value: "4.7 t" },
      { label: "First flight", value: "Sputnik-derived" },
    ],
    where: "A single orbit of the Earth at about 300 km altitude.",
    why: "The Soviet Union sought to achieve the historic first of putting a human into orbit.",
    discovered: "On 12 April 1961 Yuri Gagarin completed one orbit of Earth aboard Vostok 1, becoming the first human in space and instantly a global icon. Vostok also carried the first woman, Valentina Tereshkova, in 1963.",
    whatHappened: "On 12 April 1961, Vostok 1 carried Yuri Gagarin on a single orbit of Earth lasting 108 minutes — the first human spaceflight in history. Valentina Tereshkova flew aboard Vostok 6 in June 1963, becoming the first woman in space. Six Vostok missions flew in total.",
    destination: "LEO",
    viz: { stages: [ {len: 28, rad: 1.4}, {len: 8, rad: 1.3} ], nose: 6, fins: 0, color: "#dfe4ea", accent: "#2f5f2f", boosters: 4, boosterLen: 19, boosterRad: 1.3, tapered: true, target: "LEO" },
  },
  {
    id: "electron",
    name: "Electron",
    nickname: "The small rocket for small satellites",
    mission: "Opened frequent, dedicated launches for tiny satellites",
    country: "New Zealand / USA",
    agency: "Rocket Lab",
    builtBy: "Rocket Lab",
    firstFlight: 2017,
    status: "Active",
    facts: [
      { label: "Height", value: "18 m" },
      { label: "Engines", value: "9 (Rutherford)" },
      { label: "Payload to LEO", value: "300 kg" },
      { label: "Motors", value: "3D-printed" },
      { label: "Pumps", value: "Battery-electric" },
    ],
    where: "Low Earth orbit and Sun-synchronous orbits for small satellites.",
    why: "The boom in tiny 'CubeSats' created demand for a small, dedicated rocket instead of hitching a ride on a giant one.",
    discovered: "Electron pioneered 3D-printed, battery-powered rocket engines and made frequent small-satellite launches routine, even attempting to catch its returning booster in mid-air with a helicopter.",
    whatHappened: "Has completed more than 50 launches from New Zealand and Virginia since its first successful flight in 2018. In May 2022, Rocket Lab attempted to catch a returning first stage mid-air with a helicopter, briefly succeeding before releasing it. Electron's Rutherford engines are 3D-printed and electrically pumped — a first for any orbital rocket.",
    destination: "LEO",
    viz: { stages: [ {len: 12, rad: 0.6}, {len: 4, rad: 0.6} ], nose: 3, fins: 0, color: "#111418", accent: "#e64", boosters: 0, target: "LEO" },
  },
  {
    id: "pslv",
    name: "PSLV",
    nickname: "India's dependable satellite launcher",
    mission: "Launched Mangalyaan to Mars & Chandrayaan-1 to the Moon",
    country: "India",
    agency: "ISRO",
    builtBy: "ISRO",
    firstFlight: 1993,
    status: "Active",
    facts: [
      { label: "Height", value: "44 m" },
      { label: "Stages", value: "4" },
      { label: "Record", value: "104 sats, 1 flight" },
      { label: "Payload to LEO", value: "3.8 t" },
      { label: "Boosters", value: "up to 6" },
    ],
    where: "Sun-synchronous and transfer orbits, plus escape trajectories to the Moon and Mars.",
    why: "India built PSLV for affordable, reliable access to space for Earth-observation and interplanetary missions.",
    discovered: "PSLV launched Chandrayaan-1, which found water on the Moon, and Mangalyaan, which made India the first nation to reach Mars orbit on its first try. In 2017 it set a record by deploying 104 satellites on a single flight.",
    whatHappened: "Has flown more than 55 times since 1993 with a strong success record. In 2014 it placed Mangalyaan into a Mars transfer orbit, making India the first nation to reach Mars on its first attempt. In February 2017 it deployed a world-record 104 satellites on a single flight.",
    destination: "Mars",
    viz: { stages: [ {len: 20, rad: 1.4}, {len: 12, rad: 1.4}, {len: 6, rad: 1}, {len: 3, rad: 0.7} ], nose: 6, fins: 0, color: "#eceff2", accent: "#e67e22", boosters: 6, boosterLen: 12, boosterRad: 0.5, target: "Mars" },
  },
  {
    id: "lvm3",
    name: "LVM3",
    nickname: "India's heaviest rocket",
    mission: "Landed Chandrayaan-3 near the Moon's south pole (2023)",
    country: "India",
    agency: "ISRO",
    builtBy: "ISRO",
    firstFlight: 2017,
    status: "Active",
    facts: [
      { label: "Height", value: "43 m" },
      { label: "Boosters", value: "2 solid" },
      { label: "Payload to LEO", value: "10 t" },
      { label: "Payload to GTO", value: "4 t" },
      { label: "Also called", value: "GSLV Mk III" },
    ],
    where: "Geostationary transfer orbit and the Moon.",
    why: "India needed a heavier rocket to launch big communications satellites and crewed spacecraft without foreign help.",
    discovered: "In 2023 LVM3 launched Chandrayaan-3, making India the first country to land near the Moon's south pole and only the fourth to soft-land on the Moon at all. It is also India's planned rocket for crewed spaceflight.",
    whatHappened: "First flew a suborbital test in 2014, reaching full operational capability in 2017. On 14 July 2023 it launched Chandrayaan-3, which touched down near the Moon's south pole on 23 August 2023. India became the fourth country to soft-land on the Moon and the first to reach the south-polar region.",
    destination: "Moon",
    viz: { stages: [ {len: 25, rad: 2}, {len: 8, rad: 2}, {len: 5, rad: 2} ], nose: 8, fins: 0, color: "#eceff2", accent: "#e67e22", boosters: 2, boosterLen: 25, boosterRad: 1, target: "Moon" },
  },
  {
    id: "delta-ii",
    name: "Delta II",
    nickname: "The rover-launching workhorse",
    mission: "Launched the Spirit & Opportunity Mars rovers and Kepler",
    country: "United States",
    agency: "NASA / USAF",
    builtBy: "McDonnell Douglas / Boeing",
    firstFlight: 1989,
    status: "Retired (2018)",
    facts: [
      { label: "Height", value: "39 m" },
      { label: "Boosters", value: "3–9 solid" },
      { label: "Flights", value: "155" },
      { label: "Payload to LEO", value: "6.1 t" },
      { label: "Streak", value: "100 in a row" },
    ],
    where: "Earth orbit, the Moon, Mars and beyond.",
    why: "NASA needed a mid-sized, extremely reliable rocket for GPS satellites and a long run of planetary science missions.",
    discovered: "Delta II launched the Spirit and Opportunity rovers to Mars, the Kepler planet-hunting telescope, and the entire early GPS constellation, finishing its career with one of the best success records of any rocket.",
    whatHappened: "Flew 155 times between 1989 and 2018 with only two failures. It launched the first 24 GPS satellites, the Spirit and Opportunity Mars rovers, the Kepler space telescope, the MESSENGER Mercury orbiter, and NASA's GRAIL lunar gravity mappers. Its final flight in September 2018 carried ICESat-2.",
    destination: "Mars",
    viz: { stages: [ {len: 26, rad: 1.2}, {len: 6, rad: 1.2}, {len: 2, rad: 0.6} ], nose: 5, fins: 0, color: "#eef2f6", accent: "#1a4a8a", boosters: 6, boosterLen: 13, boosterRad: 0.5, target: "Mars" },
  },
];

export const SATELLITES = [
  {
    id: "sputnik-1",
    name: "Sputnik 1",
    nickname: "The first artificial satellite",
    mission: "Started the Space Age (1957)",
    country: "USSR",
    agency: "OKB-1",
    builtBy: "Sergei Korolev's bureau",
    firstFlight: 1957,
    status: "Reentered (1958)",
    type: "satellite",
    facts: [
      { label: "Mass", value: "84 kg" },
      { label: "Diameter", value: "58 cm" },
      { label: "Orbit", value: "215 × 939 km" },
      { label: "Signal", value: "'beep-beep'" },
      { label: "Lifetime", value: "3 months" },
    ],
    where: "Low Earth orbit, circling the planet every 96 minutes.",
    why: "The Soviet Union wanted to prove it could put an object into orbit — and demonstrate the reach of its rockets — before the United States.",
    discovered: "Its simple radio 'beep' heard worldwide announced that the Space Age had begun and triggered the Space Race. Tracking its orbit taught scientists about the density of the upper atmosphere.",
    whatHappened: "Launched on 4 October 1957 atop an R-7 rocket. It orbited Earth every 96 minutes, transmitting a steady beep on 20 and 40 MHz that was picked up by radio operators worldwide. Its batteries died after 21 days. The satellite re-entered the atmosphere and burned up on 4 January 1958.",
    destination: "LEO",
    viz: { kind: "sphere", radius: 1, antennas: 4, color: "#cfd3d8", target: "LEO" },
  },
  {
    id: "explorer-1",
    name: "Explorer 1",
    nickname: "America's first satellite",
    mission: "Discovered the Van Allen radiation belts (1958)",
    country: "United States",
    agency: "NASA / JPL",
    builtBy: "Jet Propulsion Laboratory",
    firstFlight: 1958,
    status: "Reentered (1970)",
    type: "satellite",
    facts: [
      { label: "Mass", value: "14 kg" },
      { label: "Orbit", value: "358 × 2,550 km" },
      { label: "Instrument", value: "Geiger counter" },
      { label: "Length", value: "2 m" },
      { label: "Discovery", value: "Radiation belts" },
    ],
    where: "An elongated Earth orbit reaching far out into the magnetosphere.",
    why: "The U.S. answered Sputnik by launching its own satellite carrying a radiation detector designed by physicist James Van Allen.",
    discovered: "Explorer 1's counter revealed intense belts of charged particles trapped by Earth's magnetic field — the Van Allen belts — the first major scientific discovery of the Space Age.",
    whatHappened: "Launched on 1 February 1958 aboard a Juno I rocket, three months after Sputnik. Its Geiger counter saturated at high altitudes — a puzzling result until James Van Allen realised the instrument was being overwhelmed by intense radiation trapped in Earth's magnetic field.",
    destination: "LEO",
    viz: { kind: "pencil", length: 3, radius: 0.3, color: "#e6e6e6", target: "LEO" },
  },
  {
    id: "hubble",
    name: "Hubble Space Telescope",
    nickname: "The telescope that rewrote the cosmos",
    mission: "Deep views of the universe from orbit since 1990",
    country: "USA / Europe",
    agency: "NASA / ESA",
    builtBy: "Lockheed & Perkin-Elmer",
    firstFlight: 1990,
    status: "Operational",
    type: "telescope",
    facts: [
      { label: "Mirror", value: "2.4 m" },
      { label: "Orbit", value: "~540 km" },
      { label: "Length", value: "13.2 m" },
      { label: "Speed", value: "27,000 km/h" },
      { label: "Servicing", value: "5 missions" },
    ],
    where: "Low Earth orbit, above the blur of the atmosphere.",
    why: "Astronomers wanted a telescope above the atmosphere to see the universe with unprecedented clarity across visible and ultraviolet light.",
    discovered: "Hubble measured the age of the universe (~13.8 billion years), captured the famous 'Pillars of Creation', and its Deep Field images revealed thousands of galaxies in a patch of apparently empty sky. A daring 1993 spacewalk fixed its blurry mirror.",
    whatHappened: "Deployed from Space Shuttle Discovery in April 1990. A grinding error left the primary mirror too flat by 2.2 micrometres, producing blurred images. In December 1993, astronauts installed corrective optics during a demanding series of spacewalks. Five servicing missions over 19 years have kept it at the forefront of astronomy for more than three decades.",
    destination: "LEO",
    viz: { kind: "telescope", length: 5, radius: 1.2, panels: 2, color: "#c9a227", target: "LEO" },
    anatomy: [
      { part: "Aperture Door", desc: "A lid that shields the delicate mirror from stray sunlight and space debris." },
      { part: "Primary Mirror", desc: "A 2.4-metre mirror, polished so smoothly its flaw was famously smaller than a wavelength of light — later corrected." },
      { part: "Instrument Bay", desc: "Cameras and spectrographs that split starlight into its colours to study distant galaxies." },
      { part: "Solar Arrays", desc: "Two wings of solar cells that power the telescope from sunlight." },
      { part: "Fine Guidance Sensors", desc: "Lock onto guide stars to hold the telescope rock-steady for long exposures." },
      { part: "Communications Antennas", desc: "Relay images down to Earth through NASA's tracking satellites." },
    ],
  },
  {
    id: "jwst",
    name: "James Webb Space Telescope",
    nickname: "The largest telescope ever launched",
    mission: "Seeing the first galaxies and distant worlds",
    country: "USA / EU / Canada",
    agency: "NASA / ESA / CSA",
    builtBy: "Northrop Grumman",
    firstFlight: 2021,
    status: "Operational",
    type: "telescope",
    facts: [
      { label: "Mirror", value: "6.5 m (18 segments)" },
      { label: "Location", value: "L2, 1.5M km away" },
      { label: "Sunshield", value: "Tennis-court sized" },
      { label: "Sees", value: "Infrared light" },
      { label: "Temperature", value: "−233 °C" },
    ],
    where: "The Sun–Earth L2 point, 1.5 million km beyond Earth, always facing away from the Sun.",
    why: "To see the faint infrared glow of the very first galaxies and to probe the atmospheres of planets around other stars — light too red for Hubble.",
    discovered: "Since 2022 Webb has photographed galaxies that formed within a few hundred million years of the Big Bang, detected carbon dioxide in an exoplanet's atmosphere, and delivered the deepest, sharpest infrared images of the cosmos ever taken.",
    whatHappened: "Launched on Christmas Day 2021 aboard an Ariane 5. Over the following two weeks it unfolded a tennis-court-sized sunshield and 18 gold-coated hexagonal mirror segments. It reached the L2 point in January 2022 and began science operations in July 2022 with images of unprecedented depth and clarity.",
    destination: "L2",
    viz: { kind: "webb", mirror: 3, sunshield: 6, color: "#c9a227", target: "L2" },
  },
  {
    id: "voyager-1",
    name: "Voyager 1",
    nickname: "The most distant human-made object",
    mission: "Grand Tour of the outer planets, now in interstellar space",
    country: "United States",
    agency: "NASA / JPL",
    builtBy: "Jet Propulsion Laboratory",
    firstFlight: 1977,
    status: "Active",
    type: "probe",
    facts: [
      { label: "Distance", value: "24+ billion km" },
      { label: "Speed", value: "61,000 km/h" },
      { label: "Power", value: "Nuclear (RTG)" },
      { label: "Carries", value: "Golden Record" },
      { label: "Signal delay", value: "~22 hours" },
    ],
    where: "Past Jupiter and Saturn, and since 2012 into interstellar space beyond the Sun's bubble.",
    why: "A rare planetary alignment let one spacecraft tour multiple giant planets using their gravity to slingshot onward — a chance that comes once in 175 years.",
    discovered: "Voyager 1 revealed volcanoes erupting on Jupiter's moon Io and the intricate structure of Saturn's rings. In 2012 it became the first spacecraft to leave the Sun's heliosphere, and it still whispers data across interstellar space carrying a golden record of Earth's sounds.",
    whatHappened: "Launched 5 September 1977, sixteen days after Voyager 2. Flew past Jupiter in March 1979 and Saturn in November 1980. On 14 February 1990, from 6 billion km away, it turned its camera back toward Earth and took the Pale Blue Dot photograph. On 25 August 2012 it crossed the heliopause into interstellar space.",
    destination: "Interstellar",
    viz: { kind: "probe", dish: 2.4, boom: 4, color: "#d8d8d8", target: "Interstellar" },
  },
  {
    id: "voyager-2",
    name: "Voyager 2",
    nickname: "The only probe to visit Uranus and Neptune",
    mission: "The complete Grand Tour of all four giant planets",
    country: "United States",
    agency: "NASA / JPL",
    builtBy: "Jet Propulsion Laboratory",
    firstFlight: 1977,
    status: "Active",
    type: "probe",
    facts: [
      { label: "Planets visited", value: "4" },
      { label: "Distance", value: "20+ billion km" },
      { label: "Uranus flyby", value: "1986" },
      { label: "Neptune flyby", value: "1989" },
      { label: "Power", value: "Nuclear (RTG)" },
    ],
    where: "Jupiter, Saturn, Uranus, Neptune — and now interstellar space.",
    why: "Launched to complete the Grand Tour, it took the longer path that allowed flybys of the two ice giants no spacecraft had ever seen up close.",
    discovered: "Voyager 2 remains the only spacecraft ever to visit Uranus and Neptune, discovering new moons, Neptune's supersonic winds and its Great Dark Spot. It entered interstellar space in 2018.",
    whatHappened: "Launched 20 August 1977 — before Voyager 1 despite its higher number. Flew past Jupiter (1979), Saturn (1981), Uranus (January 1986), and Neptune (August 1989), completing the only Grand Tour of all four giant planets. It crossed the heliopause into interstellar space on 5 November 2018.",
    destination: "Interstellar",
    viz: { kind: "probe", dish: 2.4, boom: 4, color: "#d8d8d8", target: "Interstellar" },
  },
  {
    id: "iss",
    name: "International Space Station",
    nickname: "Humanity's home in orbit",
    mission: "Continuously crewed since November 2000",
    country: "International",
    agency: "NASA, Roscosmos, ESA, JAXA, CSA",
    builtBy: "15 nations",
    firstFlight: 1998,
    status: "Operational",
    type: "station",
    facts: [
      { label: "Mass", value: "420 t" },
      { label: "Length", value: "109 m" },
      { label: "Orbit", value: "~410 km" },
      { label: "Speed", value: "28,000 km/h" },
      { label: "Crew", value: "Usually 7" },
    ],
    where: "Low Earth orbit, circling the planet every 90 minutes — 16 sunrises a day.",
    why: "The world's space agencies joined forces to build a permanent laboratory in microgravity and to cooperate peacefully in space after the Cold War.",
    discovered: "The most expensive object ever built, the ISS has hosted thousands of experiments on how the human body, fire, plants and materials behave in weightlessness — knowledge essential for future journeys to the Moon and Mars.",
    whatHappened: "The first module, Zarya, launched in November 1998. Continuous human habitation began in November 2000 and has not been interrupted since. More than 270 people from 20 countries have lived and worked aboard. Over 3,000 scientific experiments have been conducted in microgravity.",
    destination: "LEO",
    viz: { kind: "station", panels: 8, length: 8, color: "#cfd3d8", target: "LEO" },
  },
  {
    id: "cassini",
    name: "Cassini–Huygens",
    nickname: "The Saturn explorer",
    mission: "13 years orbiting Saturn and landing on Titan",
    country: "USA / EU / Italy",
    agency: "NASA / ESA / ASI",
    builtBy: "JPL & Alenia Spazio",
    firstFlight: 1997,
    status: "Ended (2017)",
    type: "probe",
    facts: [
      { label: "Arrived Saturn", value: "2004" },
      { label: "Orbits", value: "294" },
      { label: "Moons studied", value: "Titan, Enceladus…" },
      { label: "Lander", value: "Huygens" },
      { label: "Finale", value: "Dove into Saturn" },
    ],
    where: "Orbit around Saturn, with the Huygens probe descending to the surface of the moon Titan.",
    why: "To study Saturn, its spectacular rings and its many moons up close over many years.",
    discovered: "Cassini found geysers of water erupting from an ocean beneath the moon Enceladus and lakes of liquid methane on Titan, while Huygens returned the first pictures from Titan's surface. It ended in 2017 with a deliberate plunge into Saturn.",
    whatHappened: "Launched in October 1997. After gravity-assist flybys of Venus, Earth, and Jupiter, it entered Saturn orbit in July 2004. The Huygens probe separated and descended through Titan's thick atmosphere, landing on 14 January 2005. Cassini completed 294 orbits before a deliberate final plunge into Saturn's atmosphere on 15 September 2017.",
    destination: "Saturn",
    viz: { kind: "probe", dish: 2.4, boom: 5, color: "#caa46a", target: "Saturn" },
  },
  {
    id: "galileo",
    name: "Galileo",
    nickname: "The Jupiter orbiter",
    mission: "First spacecraft to orbit Jupiter (1995)",
    country: "United States",
    agency: "NASA / JPL",
    builtBy: "Jet Propulsion Laboratory",
    firstFlight: 1989,
    status: "Ended (2003)",
    type: "probe",
    facts: [
      { label: "Arrived Jupiter", value: "1995" },
      { label: "Atmospheric probe", value: "Yes" },
      { label: "Key moon", value: "Europa" },
      { label: "Duration", value: "8 years in orbit" },
      { label: "Finale", value: "Dove into Jupiter" },
    ],
    where: "Orbit around Jupiter, dropping a probe into the giant planet's atmosphere.",
    why: "To make the first long-term study of Jupiter, its violent atmosphere and its four large moons.",
    discovered: "Galileo found powerful evidence for a salty ocean beneath the icy crust of the moon Europa — one of the best places to search for life beyond Earth — and watched a comet crash into Jupiter.",
    whatHappened: "Launched from Space Shuttle Atlantis in October 1989. After gravity assists from Venus and Earth, it arrived at Jupiter in December 1995. Its atmospheric probe descended 160 km into Jupiter's clouds before being crushed by pressure. The orbiter spent eight years studying the Jovian system before being deliberately crashed into Jupiter in September 2003.",
    destination: "Jupiter",
    viz: { kind: "probe", dish: 1.8, boom: 5, color: "#d8d8d8", target: "Jupiter" },
  },
  {
    id: "new-horizons",
    name: "New Horizons",
    nickname: "The Pluto flyby",
    mission: "First close-up of Pluto (2015)",
    country: "United States",
    agency: "NASA / APL",
    builtBy: "Johns Hopkins APL",
    firstFlight: 2006,
    status: "Active",
    type: "probe",
    facts: [
      { label: "Pluto flyby", value: "2015" },
      { label: "Cruise", value: "9.5 years" },
      { label: "Speed", value: "58,500 km/h" },
      { label: "Also visited", value: "Arrokoth (2019)" },
      { label: "Power", value: "Nuclear (RTG)" },
    ],
    where: "Across the entire solar system to Pluto, then onward into the distant Kuiper Belt.",
    why: "Pluto was the last of the classical planets never visited by a spacecraft — a mysterious world at the frontier of the solar system.",
    discovered: "In 2015 New Horizons revealed Pluto to be a stunningly active world with a giant heart-shaped glacier of frozen nitrogen and mountains of water ice. In 2019 it flew past Arrokoth, the most distant object ever explored up close.",
    whatHappened: "Launched 19 January 2006 — the fastest spacecraft departure from Earth at 58,500 km/h. A Jupiter gravity assist in February 2007 shortened the trip by three years. On 14 July 2015 it passed 12,500 km from Pluto. On 1 January 2019 it flew past Arrokoth, the most distant object ever explored up close.",
    destination: "Pluto",
    viz: { kind: "probe", dish: 2.1, boom: 3, color: "#cbb892", target: "Pluto" },
  },
  {
    id: "curiosity",
    name: "Curiosity",
    nickname: "The nuclear-powered Mars rover",
    mission: "Exploring whether Mars could have hosted life",
    country: "United States",
    agency: "NASA / JPL",
    builtBy: "Jet Propulsion Laboratory",
    firstFlight: 2011,
    status: "Active",
    type: "rover",
    facts: [
      { label: "Landed", value: "Aug 2012" },
      { label: "Site", value: "Gale Crater" },
      { label: "Mass", value: "899 kg" },
      { label: "Power", value: "Nuclear (RTG)" },
      { label: "Distance driven", value: "30+ km" },
    ],
    where: "Gale Crater on Mars, climbing the layered slopes of a 5-km-high mountain.",
    why: "To investigate whether Mars ever had the right conditions — water, chemistry and energy — to support microbial life.",
    discovered: "Curiosity found an ancient lakebed and detected clays and organic molecules, showing that Gale Crater was once a habitable freshwater environment billions of years ago. It also measured seasonal swings of methane in the Martian air.",
    whatHappened: "Entered the Martian atmosphere on 6 August 2012 and was lowered to the surface of Gale Crater by a rocket-powered sky crane — a landing method never used before. It has since driven over 30 km, climbing the lower slopes of Mount Sharp while drilling rock samples and analysing them with on-board laboratories.",
    destination: "Mars",
    viz: { kind: "rover", length: 3, color: "#b8712d", target: "Mars" },
  },
  {
    id: "perseverance",
    name: "Perseverance",
    nickname: "The rover that's collecting Mars for return",
    mission: "Searching for ancient life & caching samples",
    country: "United States",
    agency: "NASA / JPL",
    builtBy: "Jet Propulsion Laboratory",
    firstFlight: 2020,
    status: "Active",
    type: "rover",
    facts: [
      { label: "Landed", value: "Feb 2021" },
      { label: "Site", value: "Jezero Crater" },
      { label: "Helicopter", value: "Ingenuity" },
      { label: "Samples", value: "Being cached" },
      { label: "Made oxygen", value: "MOXIE" },
    ],
    where: "Jezero Crater on Mars, the site of an ancient river delta.",
    why: "To seek signs of ancient microbial life and to collect rock samples for a future mission to bring back to Earth.",
    discovered: "Perseverance carried Ingenuity, the first aircraft to fly on another planet, and its MOXIE instrument made breathable oxygen from the Martian atmosphere. It has drilled and sealed dozens of rock cores awaiting return to Earth.",
    whatHappened: "Landed in Jezero Crater on 18 February 2021 using a sky-crane descent. On 19 April 2021 the Ingenuity helicopter achieved the first powered controlled flight on another planet, eventually completing 72 flights. Perseverance has drilled and sealed dozens of rock core samples for a future Mars Sample Return mission.",
    destination: "Mars",
    viz: { kind: "rover", length: 3, color: "#b8712d", target: "Mars" },
  },
  {
    id: "parker-solar-probe",
    name: "Parker Solar Probe",
    nickname: "The spacecraft that touched the Sun",
    mission: "Flying through the Sun's outer atmosphere",
    country: "United States",
    agency: "NASA / APL",
    builtBy: "Johns Hopkins APL",
    firstFlight: 2018,
    status: "Active",
    type: "probe",
    facts: [
      { label: "Closest approach", value: "6.1M km" },
      { label: "Speed", value: "690,000 km/h" },
      { label: "Heat shield", value: "1,370 °C" },
      { label: "Record", value: "Fastest object ever" },
      { label: "Uses", value: "Venus gravity" },
    ],
    where: "Repeated dives through the Sun's corona, closer to the Sun than any spacecraft in history.",
    why: "To solve why the Sun's corona is far hotter than its surface and what accelerates the solar wind that shapes space weather.",
    discovered: "In 2021 Parker became the first spacecraft to fly through the Sun's corona. It is the fastest object humans have ever built, and it discovered switchback-shaped kinks in the Sun's magnetic field within the solar wind.",
    whatHappened: "Launched 12 August 2018 on a Delta IV Heavy. Using a series of seven Venus gravity assists to tighten its orbit, it makes progressively closer passes of the Sun. On 28 April 2021 it became the first spacecraft to fly through the Sun's corona, directly sampling solar wind plasma and magnetic fields at close range.",
    destination: "Sun",
    viz: { kind: "probe", dish: 0, boom: 2, shield: true, color: "#e0e0e0", target: "Sun" },
  },
  {
    id: "juno",
    name: "Juno",
    nickname: "The solar-powered Jupiter orbiter",
    mission: "Peering beneath Jupiter's clouds",
    country: "United States",
    agency: "NASA / JPL",
    builtBy: "Lockheed Martin",
    firstFlight: 2011,
    status: "Active",
    type: "probe",
    facts: [
      { label: "Arrived", value: "2016" },
      { label: "Power", value: "Solar (huge panels)" },
      { label: "Orbit", value: "Polar, elliptical" },
      { label: "Studies", value: "Interior & poles" },
      { label: "Images", value: "JunoCam" },
    ],
    where: "A looping polar orbit around Jupiter, diving close to the cloud tops every few weeks.",
    why: "To look beneath Jupiter's clouds and understand how the giant planet formed, its deep structure and its powerful magnetic field.",
    discovered: "Juno revealed that Jupiter's poles are ringed by clusters of cyclones the size of Earth, mapped a surprisingly 'fuzzy' core, and returned some of the most beautiful images of the planet ever taken — all on solar power far from the Sun.",
    whatHappened: "Launched 5 August 2011 and arrived at Jupiter on 4 July 2016 after a five-year cruise. It entered a polar orbit, skimming close to the cloud tops every 53 days to peer beneath the atmosphere with microwave instruments. Its mission has been extended to include close flybys of the moons Ganymede, Europa, and Io.",
    destination: "Jupiter",
    viz: { kind: "probe", dish: 1.6, boom: 4, panels: 3, color: "#d8d8d8", target: "Jupiter" },
  },
  {
    id: "rosetta",
    name: "Rosetta & Philae",
    nickname: "The comet chaser",
    mission: "First spacecraft to orbit & land on a comet",
    country: "Europe",
    agency: "ESA",
    builtBy: "Airbus Defence and Space",
    firstFlight: 2004,
    status: "Ended (2016)",
    type: "probe",
    facts: [
      { label: "Target", value: "Comet 67P" },
      { label: "Arrived", value: "2014" },
      { label: "Lander", value: "Philae" },
      { label: "Journey", value: "10 years, 6B km" },
      { label: "Slept", value: "31 months in hibernation" },
    ],
    where: "Chased and orbited Comet 67P/Churyumov–Gerasimenko, then dropped the Philae lander onto its surface.",
    why: "Comets are frozen leftovers from the birth of the solar system; studying one up close reveals what the early solar system was made of.",
    discovered: "In 2014 Philae became the first probe to land on a comet. Rosetta found the comet's water differed from Earth's oceans and detected the building blocks of life — including the amino acid glycine — in the comet's dusty halo.",
    whatHappened: "Launched 2 March 2004. After three Earth gravity assists and one Mars flyby over ten years, it rendezvoused with Comet 67P on 6 August 2014. The Philae lander touched down on 12 November 2014, bouncing twice before settling in a shadowed crevice. Rosetta ended with a controlled impact on the comet on 30 September 2016.",
    destination: "Comet",
    viz: { kind: "probe", dish: 2.2, boom: 3, panels: 4, color: "#d8d8d8", target: "Comet" },
  },
  {
    id: "kepler",
    name: "Kepler",
    nickname: "The planet hunter",
    mission: "Discovering thousands of worlds around other stars",
    country: "United States",
    agency: "NASA",
    builtBy: "Ball Aerospace",
    firstFlight: 2009,
    status: "Retired (2018)",
    type: "telescope",
    facts: [
      { label: "Planets found", value: "2,600+" },
      { label: "Method", value: "Star dimming" },
      { label: "Stars watched", value: "150,000+" },
      { label: "Orbit", value: "Around the Sun" },
      { label: "Field", value: "One patch of sky" },
    ],
    where: "An orbit around the Sun trailing Earth, staring at a single patch of sky for years.",
    why: "To find out how common Earth-like planets are by watching for the tiny dimming as planets crossed in front of their stars.",
    discovered: "Kepler discovered more than 2,600 confirmed exoplanets and showed that planets outnumber stars in our galaxy — transforming the search for another Earth from science fiction into statistics.",
    whatHappened: "Launched 7 March 2009 into an Earth-trailing orbit around the Sun. It monitored 150,000 stars in the constellation Cygnus for years, measuring tiny brightness dips caused by transiting planets. Two of four reaction wheels failed in 2013; the mission was repurposed as K2 and continued discovering planets until fuel ran out in October 2018.",
    destination: "Sun",
    viz: { kind: "telescope", length: 4.7, radius: 1.4, panels: 1, color: "#c9a227", target: "Sun" },
  },
  {
    id: "viking-1",
    name: "Viking 1",
    nickname: "The first successful Mars landing",
    mission: "First long-lived lander on Mars (1976)",
    country: "United States",
    agency: "NASA",
    builtBy: "Martin Marietta",
    firstFlight: 1975,
    status: "Ended (1982)",
    type: "lander",
    facts: [
      { label: "Landed", value: "Jul 1976" },
      { label: "Site", value: "Chryse Planitia" },
      { label: "Two parts", value: "Orbiter + lander" },
      { label: "Searched for", value: "Life" },
      { label: "Duration", value: "6 years" },
    ],
    where: "The Chryse Planitia plains of Mars, with a companion orbiter mapping from above.",
    why: "To return the first images from the Martian surface and to run experiments searching for signs of life in the soil.",
    discovered: "Viking 1 sent home the first pictures ever taken from the surface of Mars and made the first direct search for life there. Its biology experiments were famously inconclusive, sparking debates that continue today.",
    whatHappened: "Launched 20 August 1975 and entered Mars orbit on 19 June 1976. The lander separated and touched down on Chryse Planitia on 20 July 1976 — the first successful Mars landing. It transmitted the first photographs from the Martian surface and operated for more than six years until a faulty software update ended communications.",
    destination: "Mars",
    viz: { kind: "lander", length: 2.5, color: "#c98a4a", target: "Mars" },
  },
  {
    id: "telstar-1",
    name: "Telstar 1",
    nickname: "The first communications satellite",
    mission: "First live transatlantic TV broadcast (1962)",
    country: "United States",
    agency: "AT&T / Bell Labs",
    builtBy: "Bell Telephone Laboratories",
    firstFlight: 1962,
    status: "Inactive (still in orbit)",
    type: "satellite",
    facts: [
      { label: "Mass", value: "77 kg" },
      { label: "Shape", value: "Sphere" },
      { label: "Orbit", value: "Elliptical" },
      { label: "First", value: "Live TV across ocean" },
      { label: "Powered", value: "Solar cells" },
    ],
    where: "An elliptical Earth orbit that briefly linked North America and Europe on each pass.",
    why: "To prove that satellites could relay live television, telephone calls and data across the ocean instantly.",
    discovered: "In July 1962 Telstar relayed the first live television pictures between the United States and Europe, launching the age of global satellite communication that connects the world today.",
    whatHappened: "Launched 10 July 1962 on a Delta rocket. Hours later it relayed the first live transatlantic television signal — a broadcast received in Pleumeur-Bodou, France and Goonhilly Downs, England. Radiation from high-altitude nuclear tests degraded its transistors over the following months, and it went silent in February 1963.",
    destination: "LEO",
    viz: { kind: "sphere", radius: 1, antennas: 0, faceted: true, color: "#cfd3d8", target: "LEO" },
  },
  {
    id: "chandrayaan-3",
    name: "Chandrayaan-3",
    nickname: "The Moon's south-pole pioneer",
    mission: "First landing near the lunar south pole (2023)",
    country: "India",
    agency: "ISRO",
    builtBy: "ISRO",
    firstFlight: 2023,
    status: "Mission complete",
    type: "lander",
    facts: [
      { label: "Landed", value: "Aug 2023" },
      { label: "Lander", value: "Vikram" },
      { label: "Rover", value: "Pragyan" },
      { label: "Region", value: "South pole" },
      { label: "Milestone", value: "4th nation to land" },
    ],
    where: "The rugged, crater-strewn south-polar region of the Moon.",
    why: "The Moon's south pole holds water ice in permanently shadowed craters — a vital resource for future exploration — but is difficult to reach.",
    discovered: "In 2023 Chandrayaan-3 made India the first nation to land near the lunar south pole and the fourth ever to soft-land on the Moon. Its Pragyan rover confirmed sulphur and other elements in the soil.",
    whatHappened: "Launched 14 July 2023 aboard an LVM3 rocket. After weeks in progressively wider Earth orbits and a lunar transfer, the Vikram lander touched down near the south pole on 23 August 2023. The Pragyan rover deployed and spent 14 Earth days traversing the surface before entering hibernation at lunar nightfall.",
    destination: "Moon",
    viz: { kind: "lander", length: 2.2, color: "#d0b26a", target: "Moon" },
  },
  {
    id: "gaia",
    name: "Gaia",
    nickname: "The galaxy mapmaker",
    mission: "Charting a billion stars in 3D",
    country: "Europe",
    agency: "ESA",
    builtBy: "Airbus Defence and Space",
    firstFlight: 2013,
    status: "Ended (2025)",
    type: "telescope",
    facts: [
      { label: "Stars mapped", value: "~2 billion" },
      { label: "Location", value: "L2" },
      { label: "Precision", value: "Extraordinary" },
      { label: "Spins", value: "Every 6 hours" },
      { label: "Made", value: "3D galaxy map" },
    ],
    where: "The Sun–Earth L2 point, slowly spinning to scan the entire sky again and again.",
    why: "To measure the exact positions, distances and motions of a billion stars and build the most detailed three-dimensional map of the Milky Way ever made.",
    discovered: "Gaia pinpointed nearly two billion stars, revealing the Milky Way's warped, rippling shape and the scars of ancient galaxy collisions — a catalogue that underpins a huge fraction of modern astronomy.",
    whatHappened: "Launched 19 December 2013 to the Sun-Earth L2 point. For over a decade it spun slowly, scanning the entire sky repeatedly to measure the precise positions, distances, and motions of nearly two billion stars. Its successive data releases have reshaped the field of stellar astronomy and our understanding of the Milky Way's history.",
    destination: "L2",
    viz: { kind: "telescope", length: 3, radius: 2, panels: 0, skirt: true, color: "#b8bcc0", target: "L2" },
  },
];

export const SECTIONS = {
  rockets: { title: "Rockets", items: ROCKETS, accent: "#ff7a3d" },
  satellites: { title: "Satellites", items: SATELLITES, accent: "#4db8ff" },
};

// Flagship items whose "Anatomy / Parts" view is featured first.
export const FLAGSHIP = { rockets: "saturn-v", satellites: "hubble" };
